version: '3'
services:
  www:
    build:
      context: .
      dockerfile: Dockerfile_www
    ports:
    - "5000:5000"
    volumes:
    - .:/app
    links:
    - redis
  bot:
    build:
      context: .
      dockerfile: Dockerfile_bot
    volumes:
      - .:/app
    links:
    - redis
  redis:
    image: redis
    volumes:
      - ./db:/data
volumes:
  wwwlog: {}
  botlog: {}
